import './globals.scss'
import { roboto } from './fonts';


export const metadata = {
  title: 'MF test app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body >
        {children}
      </body>
    </html>
  )
}
